export { templates as identifierTemplates };

const templates = [
  "name",
  "oYccTok3tA",
  "s51LggxsXO",
  "LFnqB$u3u2J",
  "RVHJgElY7IMa",
  "eg9xKgLDDkge",
  "QgZDIA9G5h2A0jYGV3F9",
  "eXUU6484P0t",
  "ssT0utkp1VE",
  "LyHBWPgGM",
  "wXR$QU4l$sMLAOmkvAEv",
  "asuiVBcQrQehVWw",
  "gQ$AdCtdFHLtyNKrX2yCrr2D6fy",
  "OvqckARsLPa",
  "Tkyo3UbaGjsgSQcAh5g",
  "u77S4Qw4EcXXeR6NGmvuWY",
  "mEGJh28iU9ND8ErEy2XkxO7o",
  "WDQ2SyynXd6zztx",
  "ias_Jzy6YpQ2Fog",
  "o",
  "xGFkEqLuJa",
  "$",
  "___$1",
];
